<?php
require_once __DIR__ . '/bootstrap.php';
$topics = [];
if (isset($conn) && !$conn->connect_error) {
    $sql = "SELECT t.*, c.name category_name, c.color category_color, u.username FROM topics t JOIN categories c ON c.id=t.category_id JOIN users u ON u.id=t.user_id WHERE t.is_approved=1 ORDER BY t.is_pinned DESC, t.last_post_at DESC LIMIT 12";
    if ($result = $conn->query($sql)) while ($row = $result->fetch_assoc()) $topics[] = $row;
}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nexo — comunidad sin ruido</title><link rel="stylesheet" href="assets/css/nexo.css"></head><body>
<header class="topbar"><a class="brand" href="index.php"><span class="brand-mark">N</span><span>NEXO</span></a><nav><a href="index.php">Explorar</a><a href="members.php">Miembros</a><a href="about.php">Manifiesto</a></nav><div class="top-actions"><a class="search" href="search.php">⌕ Buscar</a><?php if(auth()): ?><a class="avatar" href="profile.php"><?=e($_SESSION['user']['username'][0])?></a><?php else: ?><a class="button ghost" href="login.php">Entrar</a><a class="button" href="register.php">Unirme</a><?php endif; ?></div></header>
<main class="shell"><section class="hero"><div><span class="eyebrow">COMUNIDAD DIGITAL · 2026</span><h1>Ideas que encuentran<br><em>su conexión.</em></h1><p>Un espacio con intención para conversar, crear y aprender junto a personas curiosas.</p><div class="hero-actions"><a class="button" href="new-topic.php">Iniciar una conversación <span>→</span></a><a class="text-link" href="#feed">Ver actividad ↓</a></div></div><div class="orb"><div class="orb-core">N</div><span class="orbit-dot dot-one"></span><span class="orbit-dot dot-two"></span></div></section>
<section class="stats"><div><strong>12.8k</strong><span>miembros activos</span></div><div><strong>48.2k</strong><span>conexiones creadas</span></div><div><strong>99%</strong><span>buena energía</span></div><div class="status"><i></i> Todo funcionando</div></section>
<section id="feed" class="content-grid"><div class="feed"><div class="section-head"><div><span class="eyebrow">LO ÚLTIMO</span><h2>Conversaciones destacadas</h2></div><a class="text-link" href="topics.php">Ver todo →</a></div><?php if (!$topics): ?><div class="empty"><span>✦</span><h3>El espacio está esperando tu primera idea</h3><p>Importa una conversación y empieza a conectar con la comunidad.</p><a class="button" href="register.php">Crear cuenta</a></div><?php else: foreach($topics as $topic): ?><article class="topic-card"><div class="topic-icon" style="--accent:<?=e($topic['category_color'])?>">✦</div><div class="topic-main"><div class="topic-meta"><span style="color:<?=e($topic['category_color'])?>"><?=e($topic['category_name'])?></span><span>· <?=e($topic['username'])?></span></div><h3><a href="topic.php?id=<?=e($topic['id'])?>"><?=e($topic['title'])?></a></h3><p><?=e($topic['description'] ?: 'Una conversación abierta de la comunidad Nexo.')?></p><div class="topic-foot"><span>◌ <?=e($topic['replies'])?> respuestas</span><span>◉ <?=e($topic['views'])?> vistas</span><span><?=e($topic['last_post_at'] ?: $topic['created_at'])?></span></div></div><span class="arrow">↗</span></article><?php endforeach; endif; ?></div><aside class="side-panel"><div class="panel-card gradient-card"><span class="eyebrow">NEXO NOTE</span><h3>La calidad de una comunidad se mide por lo que hace posible.</h3><a href="about.php" class="text-link">Conoce nuestro manifiesto →</a></div><div class="panel-card"><div class="section-head compact"><h3>Espacios</h3><a href="categories.php">+</a></div><a class="space" href="topics.php?category=1"><b class="space-icon cyan">✦</b><span><strong>General</strong><small>1,240 conversaciones</small></span><i>→</i></a><a class="space" href="topics.php?category=2"><b class="space-icon purple">⌘</b><span><strong>Creadores</strong><small>892 conversaciones</small></span><i>→</i></a><a class="space" href="topics.php?category=3"><b class="space-icon green">⌁</b><span><strong>Tecnología</strong><small>2,103 conversaciones</small></span><i>→</i></a></div></aside></section></main><footer><span>© 2026 Nexo</span><span>Hecho con intención para conversaciones reales.</span><a href="admin/">Panel de administración</a></footer></body></html>
