CREATE DATABASE IF NOT EXISTS nexo_forum CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nexo_forum;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, email VARCHAR(120) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, avatar VARCHAR(255) NULL, bio TEXT NULL, role ENUM('member','moderator','admin') NOT NULL DEFAULT 'member', status ENUM('active','inactive','banned') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE, description TEXT NULL, icon VARCHAR(20) NULL, color VARCHAR(7) NOT NULL DEFAULT '#6be7ed', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE topics (id INT AUTO_INCREMENT PRIMARY KEY, category_id INT NOT NULL, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL UNIQUE, description TEXT NULL, content LONGTEXT NOT NULL, views INT NOT NULL DEFAULT 0, replies INT NOT NULL DEFAULT 0, is_pinned TINYINT(1) NOT NULL DEFAULT 0, is_locked TINYINT(1) NOT NULL DEFAULT 0, is_approved TINYINT(1) NOT NULL DEFAULT 1, last_post_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE posts (id INT AUTO_INCREMENT PRIMARY KEY, topic_id INT NOT NULL, user_id INT NOT NULL, content LONGTEXT NOT NULL, likes INT NOT NULL DEFAULT 0, is_approved TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(topic_id) REFERENCES topics(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE reports (id INT AUTO_INCREMENT PRIMARY KEY, reporter_id INT NOT NULL, topic_id INT NULL, post_id INT NULL, reason VARCHAR(100) NOT NULL, description TEXT NULL, status ENUM('open','resolved','rejected') DEFAULT 'open', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE notifications (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, type VARCHAR(30) NOT NULL, title VARCHAR(255) NOT NULL, link VARCHAR(255) NULL, is_read TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO categories(name,slug,description,icon,color) VALUES ('General','general','Conversaciones para todo el mundo','✦','#6be7ed'),('Creadores','creadores','Diseño, proyectos e ideas','⌘','#a991ff'),('Tecnología','tecnologia','Herramientas y futuro digital','⌁','#86e4a8');
