<?php
require_once __DIR__ . '/../bootstrap.php';
if (!isAdmin()) { http_response_code(403); exit('Acceso reservado a administradores.'); }
$stats = [];
foreach ([
    'users' => 'SELECT COUNT(*) total FROM users',
    'topics' => 'SELECT COUNT(*) total FROM topics',
    'posts' => 'SELECT COUNT(*) total FROM posts',
    'reports' => "SELECT COUNT(*) total FROM reports WHERE status='open'"
] as $key => $sql) { $r = $conn->query($sql); $stats[$key] = (int)$r->fetch_assoc()['total']; }
$recent = $conn->query("SELECT id,username,role,status,created_at FROM users ORDER BY created_at DESC LIMIT 8");
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administración · Nexo</title><link rel="stylesheet" href="../assets/css/nexo.css"><link rel="stylesheet" href="admin.css"></head><body><header class="topbar"><a class="brand" href="../index.php"><span class="brand-mark">N</span><span>NEXO</span></a><nav><a href="../index.php">Volver al foro</a><a href="users.php">Usuarios</a><a href="topics.php">Contenido</a><a href="categories.php">Categorías</a><a href="reports.php">Reportes</a></nav><div class="top-actions"><a class="text-link" href="../logout.php">Salir</a></div></header><main class="admin-shell"><div class="admin-heading"><div><span class="eyebrow">CONTROL CENTRAL</span><h1>Panel de administración</h1><p>Gestiona Nexo con claridad y control.</p></div></div><section class="admin-stats"><div><span>Miembros</span><strong><?=$stats['users']?></strong></div><div><span>Conversaciones</span><strong><?=$stats['topics']?></strong></div><div><span>Respuestas</span><strong><?=$stats['posts']?></strong></div><div class="warning"><span>Reportes abiertos</span><strong><?=$stats['reports']?></strong></div></section><section class="admin-grid"><div class="admin-card"><div class="admin-card-head"><h2>Acciones rápidas</h2></div><div class="quick-actions"><a href="users.php">◉ Gestionar usuarios</a><a href="topics.php">✦ Moderar contenido</a><a href="categories.php">⌁ Editar categorías</a><a href="reports.php">⚑ Revisar reportes</a></div></div><div class="admin-card"><div class="admin-card-head"><h2>Últimos miembros</h2><a href="users.php">Ver todos →</a></div><div class="admin-table"><div class="table-row table-head"><span>Usuario</span><span>Rol</span><span>Estado</span></div><?php while($u=$recent->fetch_assoc()): ?><div class="table-row"><span><b><?=e($u['username'])?></b><small><?=e($u['created_at'])?></small></span><span class="tag"><?=e($u['role'])?></span><span class="status-dot <?=e($u['status'])?>"><?=e($u['status'])?></span></div><?php endwhile; ?></div></div></section></main></body></html>